### PR TITLE
18 signed vector angle

### PR DESCRIPTION
**Pull request by JonasWard**

### CODE REVIEW

**Comment by ccc159** [comment]
1. Is there a reason not to have the unsigned vector angle function?

2. I feel `PositiveVectorAngle` and `VectorAngle` function could be combined in a way. (Like adding the `reference` to `VectorAngle` function.)

3. What about changing positive to unsigned, or they are different?

**Comment by JonasWard** [comment]
1. without the reference vector / plane you are always calculating the smallest angle. Sometimes though, especially in 2D, you want to know the angle between two vectors in respect to the order they are positioned

2. giving an optional 3d vector / plane to the vector angle method would practically be the same but a bit less explicit so it's as you wish? it's a slightly more expensive method  but not sure that is important? :)

3. unsigned is not the right word. signed and positive are the same though because angles are periodic (-PI === PI) so it's just a matter of convention whether you return angles [0, 2PI] or [-PI, PI], I choose the former (:

**Comment by ccc159** [comment]
Ah I see. Can we do it like:

Add optional `reference` to `VectorAngle` function.

The `PositiveVectorAngle` uses the `VectorAngle` function can turn it into periodic angles?

**Comment by ccc159** [comment]
@JonasWard Is it still something you would amend or shall I take it over?

**Comment by JonasWard** [comment]
@jch I just pushed a commit, it's like you suggested but for clarity, I kept the positive angle method as a private static method around for legibility? Do you agree, or you think it should be one method (:

**Comment by ccc159** [comment]
it looks like these two functions actually do the same thing.. the `VectorAngle` funtion would also not return any negative value.

Below is the implementatoin from rhinocommon, which results the same from what I read.


```csharp
/// <summary>
    /// Computes the angle on a plane between two vectors.
    /// </summary>
    /// <param name="a">First vector.</param>
    /// <param name="b">Second vector.</param>
    /// <param name="plane">Two-dimensional plane on which to perform the angle measurement.</param>
    /// <returns>On success, the angle (in radians) between a and b as projected onto the plane; RhinoMath.UnsetValue on failure.</returns>
    public static double VectorAngle(Vector3d a, Vector3d b, Plane plane)
    {
      { // Project vectors onto plane.
        Point3d pA = plane.Origin + a;
        Point3d pB = plane.Origin + b;

        pA = plane.ClosestPoint(pA);
        pB = plane.ClosestPoint(pB);

        a = pA - plane.Origin;
        b = pB - plane.Origin;
      }

      // Abort on invalid cases.
      if (!a.Unitize()) { return RhinoMath.UnsetValue; }
      if (!b.Unitize()) { return RhinoMath.UnsetValue; }

      double dot = a * b;
      { // Limit dot product to valid range.
        if (dot >= 1.0)
        { dot = 1.0; }
        else if (dot < -1.0)
        { dot = -1.0; }
      }

      double angle = Math.Acos(dot);
      { // Special case (anti)parallel vectors.
        if (Math.Abs(angle) < 1e-64) { return 0.0; }
        if (Math.Abs(angle - Math.PI) < 1e-64) { return Math.PI; }
      }

      Vector3d cross = Vector3d.CrossProduct(a, b);
      if (plane.ZAxis.IsParallelTo(cross) == +1)
        return angle;
      return 2.0 * Math.PI - angle;
    }
```

**Comment by ccc159** [comment]
image

**Comment by JonasWard** [comment]
yes, but, they project onto a plane first, which is the same as me doing the plane to plane transformation, and then checking the crossproduct of the pair with the plane to check whether the direction is opposing, which I don't have to do because I reduced the problem to a 2D angle calculation (:

**Comment by JonasWard** [comment]
if you think it should be one method sure! but the result is for sure different when using both methods! 
Screenshot 2023-03-20 at 22 14 56

**Review by ccc159 — APPROVED** [review]

**Pull request merged**
